# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\"\x14\n\x12ListCoursesRequest\"m\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\npopularity\x18\x05 \x01(\x02\x12\r\n\x05level\x18\x06 \x01(\t\"6\n\x13ListCoursesResponse\x12\x1f\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x0e.course.Course2W\n\rCourseService\x12\x46\n\x0bListCourses\x12\x1a.course.ListCoursesRequest\x1a\x1b.course.ListCoursesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTCOURSESREQUEST']._serialized_start=24
  _globals['_LISTCOURSESREQUEST']._serialized_end=44
  _globals['_COURSE']._serialized_start=46
  _globals['_COURSE']._serialized_end=155
  _globals['_LISTCOURSESRESPONSE']._serialized_start=157
  _globals['_LISTCOURSESRESPONSE']._serialized_end=211
  _globals['_COURSESERVICE']._serialized_start=213
  _globals['_COURSESERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
