# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\";\n\x19GetRecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05top_k\x18\x02 \x01(\x05\"2\n\x0eRecommendation\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\"f\n\x1aGetRecommendationsResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x37\n\x0frecommendations\x18\x02 \x03(\x0b\x32\x1e.recommendation.Recommendation\"J\n\x15SubmitFeedbackRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"(\n\x16SubmitFeedbackResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe5\x01\n\x15RecommendationService\x12k\n\x12GetRecommendations\x12).recommendation.GetRecommendationsRequest\x1a*.recommendation.GetRecommendationsResponse\x12_\n\x0eSubmitFeedback\x12%.recommendation.SubmitFeedbackRequest\x1a&.recommendation.SubmitFeedbackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_start=40
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_end=99
  _globals['_RECOMMENDATION']._serialized_start=101
  _globals['_RECOMMENDATION']._serialized_end=151
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_start=153
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_end=255
  _globals['_SUBMITFEEDBACKREQUEST']._serialized_start=257
  _globals['_SUBMITFEEDBACKREQUEST']._serialized_end=331
  _globals['_SUBMITFEEDBACKRESPONSE']._serialized_start=333
  _globals['_SUBMITFEEDBACKRESPONSE']._serialized_end=373
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=376
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=605
# @@protoc_insertion_point(module_scope)
