# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\xb9\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tinterests\x18\x03 \x03(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12<\n\x12levels_by_interest\x18\x05 \x03(\x0b\x32 .user.User.LevelsByInterestEntry\x1a\x37\n\x15LevelsByInterestEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32:\n\x0bUserService\x12+\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\n.user.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER_LEVELSBYINTERESTENTRY']._loaded_options = None
  _globals['_USER_LEVELSBYINTERESTENTRY']._serialized_options = b'8\001'
  _globals['_GETUSERREQUEST']._serialized_start=20
  _globals['_GETUSERREQUEST']._serialized_end=53
  _globals['_USER']._serialized_start=56
  _globals['_USER']._serialized_end=241
  _globals['_USER_LEVELSBYINTERESTENTRY']._serialized_start=186
  _globals['_USER_LEVELSBYINTERESTENTRY']._serialized_end=241
  _globals['_USERSERVICE']._serialized_start=243
  _globals['_USERSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
