apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coursematch-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: coursematch.local
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8001
          - path: /api/courses/?(.*)
            pathType: Prefix
            backend:
              service:
                name: course-service
                port:
                  number: 8002
          - path: /api/recommendations/?(.*)
            pathType: Prefix
            backend:
              service:
                name: recommendation-service
                port:
                  number: 8004
