apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: coursematch

  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: recommendation-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
              name: http
          env:
            - name: TOP_K_DEFAULT
              value: "5"

            # ✅ DB (Postgres reco)
            - name: DATABASE_URL
              value: postgresql+asyncpg://postgres:ihssane%402003I@reco-postgres:5432/reco_db

            # ✅ HTTP base URLs (microservices)
            # User service (si dans default)
            - name: USER_BASE_URL
              value: http://user-service:8080

            # Course service (chez ton ami dans namespace coursematch, port 8081)
            - name: COURSE_BASE_URL
              value: http://course-service:8081
